pipeline { 
    agent any
    environment {
        aws_region = 'us-east-1'
        aws_credentials = 'Jenkins-with-Beanstalk-Credentials'
        aws_application_name = 'diagnostic-server'
        aws_environment_name = 'Diagnostic-server-dev'
    }
    stages { 
        stage('Build') { 
            steps {
                sh 'python3 -m venv venv && . venv/bin/activate && pip install -r requirements.txt && zip -r flask_app.zip .'
                sh 'ls -l flask_app.zip'
            }
        }
        stage('Test') {
            steps {
                script {
                    sh ". venv/bin/activate && pytest -v --tb=no"
                }
            }
        }
        stage('Deploy') {
            steps {
                step([$class: 'AWSEBDeploymentBuilder', applicationName: aws_application_name,
                          environmentName: aws_environment_name, awsRegion: aws_region, credentialId: aws_credentials,versionLabelFormat: "${BUILD_NUMBER}", rootObject: 'flask_app.zip'])
                
            }
        }
    }
}